name: Deploy Vue to Aliyun ECS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Vue project
        run: npm run build
       # 使用 SCP 传输文件
      - name: Upload dist contents to ECS server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          port: ${{ secrets.ALIYUN_SSH_PORT || 22 }}
          source: "dist/*"  # 只上传 dist 目录下的内容
          target: "/tmp/vue-dist-${{ github.run_id }}/"  # 使用唯一临时目录
      # ssh 登录ECS server 执行远程命令清理和重载   
      - name: Deploy and Reload Nginx
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          port: ${{ secrets.ALIYUN_SSH_PORT || 22 }}
          script: |
            # 确保目标目录存在
            mkdir -p /www/wwwroot/lumao.local.com
            
            # 关键修改：同步临时目录内容到目标目录（不带 dist 层级）
            rsync -a --delete /tmp/vue-dist-${{ github.run_id }}/dist/ /www/wwwroot/lumao.local.com/
            
            # 设置权限
            chown -R www:www /www/wwwroot/lumao.local.com
            chmod -R 755 /www/wwwroot/lumao.local.com
            
            # 清理临时文件
            rm -rf /tmp/vue-dist-${{ github.run_id }}
            
            # 重载Nginx
            nginx -t && nginx -s reload